--Below users will not required in production hence commented out
-- Insert into [tblUser] (UserID,UserName,User_Loc,UserLevel) values ('Meghana.Vedpathak@defradev.onmicrosoft.com','Meghana Vedpathak','13',1)
-- GO
-- Insert into [tblUser] (UserID,UserName,User_Loc,UserLevel) values ('Edward.Fernandes@defradev.onmicrosoft.com','Edward Fernandes','13',1)