name: build and sonar analyze template
on:
  workflow_call:
     inputs:
      repository:
        description: "docker repository name"
        required: true
        type: string
      secrets:
        SONAR_TOKEN:
          required: true

env:
  REPOSITORY: ${{ inputs.repository }}

jobs:
  build-and-sonar-analyze:
    name: build-and-sonar-analyze
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      should_push: ${{ steps.check_commit.outputs.should_push }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      
      - name: Read version from VERSION file
        id: versioning
        shell: pwsh
        run: |
          $version = Get-Content VERSION -Raw
          $version = $version.Trim()
          "version=v$version" >> $env:GITHUB_OUTPUT
          
      - name: Extract short SHA
        id: shortsha
        shell: pwsh
        run: |
          "shortsha=$($env:GITHUB_SHA.Substring(0, 8))" >> $env:GITHUB_OUTPUT

      - name: Check last commit message for 'ecrpush'
        id: check_commit
        shell: bash
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          echo "Last commit message: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" == *"ecrpush"* ]]; then
            echo "should_push=true"
            echo "should_push=true" >> $GITHUB_OUTPUT
          else
            echo "should_push=false"
            echo "should_push=false" >> $GITHUB_OUTPUT
          fi
    
      - name: Start Sonar Analysis
        shell: pwsh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin `
            /k:"DEFRA_apha-bst" `
            /o:"defra" `
            /d:sonar.token="$env:SONAR_TOKEN" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /v:"${{ steps.imgtag.outputs.image_tag }}" `
            /d:sonar.cs.opencover.reportsPaths="src/TestResults/*.coverage.opencover.xml" `
            /d:sonar.cs.vstest.reportsPaths="src/TestResults/*.test_results.trx" `
            /d:sonar.branch.name="${{ github.ref_name }}" `
            /d:sonar.verbose=true `
            /d:sonar.exclusions="**/wwwroot/**" `
            /d:sonar.coverage.exclusions="**/wwwroot/**,**/*.cshtml,**/Interfaces/*.cs,**/*Map.cs,**/*Mapper.cs,**/Program.cs,**/Startup.cs,**/DTOs/*.cs,**/Entities/*.cs,**/Models/*.cs"
      - name: Restore NuGet packages
        shell: pwsh
        run: dotnet restore src/Apha.BST.sln
      - name: Build Solution
        shell: pwsh
        run: dotnet build src/Apha.BST.sln --configuration Release
      - name: Run Unit Tests with Coverage
        shell: pwsh
        run: >
          dotnet test src/Apha.BST/Apha.BST.Application.UnitTests/Apha.BST.Application.UnitTests.csproj `
            --no-build --configuration Release /p:CollectCoverage=true `
            /p:CoverletOutput="$($PWD.Path)/src/TestResults/Apha.BST.Application.coverage.opencover.xml" `
            /p:CoverletOutputFormat=opencover `
            /p:Deterministic=true `
            /p:DebugType=full /p:DebugSymbols=true `
            --logger "trx;LogFileName=$($PWD.Path)/src/TestResults/Apha.BST.Application.test_results.trx"

          dotnet test src/Apha.BST/Apha.BST.Web.UnitTests/Apha.BST.Web.UnitTests.csproj `
            --no-build --configuration Release /p:CollectCoverage=true `
            /p:CoverletOutput="$($PWD.Path)/src/TestResults/Apha.BST.Web.coverage.opencover.xml" `
            /p:CoverletOutputFormat=opencover `
            /p:Deterministic=true `
            /p:DebugType=full /p:DebugSymbols=true `
            --logger "trx;LogFileName=$($PWD.Path)/src/TestResults/Apha.BST.Web.test_results.trx"
            
          dotnet test src/Apha.BST/Apha.BST.DataAccess.UnitTests/Apha.BST.DataAccess.UnitTests.csproj `
            --no-build --configuration Release /p:CollectCoverage=true `
            /p:CoverletOutput="$($PWD.Path)/src/TestResults/Apha.BST.DataAccess.coverage.opencover.xml" `
            /p:CoverletOutputFormat=opencover `
            /p:Deterministic=true `
            /p:DebugType=full /p:DebugSymbols=true `
            --logger "trx;LogFileName=$($PWD.Path)/src/TestResults/Apha.BST.DataAccess.test_results.trx"
      - name: List coverage files
        shell: pwsh
        run: Get-ChildItem -Recurse -Filter "*.coverage.opencover.xml"; Get-ChildItem -Recurse -Filter "*.test_results.trx"
      - name: End Sonar Analysis
        shell: pwsh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="$env:SONAR_TOKEN"
