name: Create DEV Image Version and Push ECR

on:
  workflow_dispatch:
    inputs:
      DEVIMAGEVERSION:
        description: 'DEV Image Version'
        type: string
        required: true

jobs:
  push-image:
    uses: ./.github/workflows/push-image-template.yml
    with:
      IMAGE_VERSION: ${{ github.event.inputs.DEVIMAGEVERSION }}
    secrets:
      AWS_ENV_REGION: ${{ secrets.AWS_ENV_REGION }}
      AWS_ENV_ACCOUNT: ${{ secrets.AWS_ENV_ACCOUNT }}
      AWS_ENV_ROLE: ${{ secrets.AWS_ENV_ROLE }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
