name: Create PROD Application Release
on:
  workflow_dispatch:
    inputs:
      APPLICATIONRELEASEVERSION:
        description: 'PROD Application Release Version'
        type: string
        required: true

env:
  REPOSITORY: apha/bst
jobs:
  application-release:
    name: prod-application-release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Validate VERSION format (major.minor.patch)
        shell: bash
        run: |
          VERSION="${{ github.event.inputs.APPLICATIONRELEASEVERSION }}"
          # Each segment: 0 or 1–999 (no leading zeros). Disallow the all-zero version 0.0.0.
          if [[ ! "$VERSION" =~ ^(?!0\.0\.0$)(?:0|[1-9][0-9]{0,2})\.(?:0|[1-9][0-2][0-9]{0,2}|[1-9][0-9]{0,2})\.(?:0|[1-9][0-9]{0,2})$ ]]; then
            echo "Invalid VERSION: $VERSION"
            echo "Expected: major.minor.patch where each is 0–999 (e.g., 1.0.0, 2.10.3, 0.9.12). 0.0.0 is not allowed."
            exit 1
          fi
      

