name: Dev Build and Sonar Analysis

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'feature/*'
  #     - 'fix/*'
  #     - 'docs/*'

jobs:
  build-and-analyze:
    name: Versioning Only
    runs-on: windows-latest

    steps:
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: 17
      #     distribution: 'zulu'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --------------------- Versioning Step ----------------------
      - name: Bump version from commit
        id: versioning
        shell: pwsh
        run: |
          $CommitMsg = "${{ github.event.head_commit.message }}"
          ./scripts/bump-version.ps1 -CommitMsg $CommitMsg

      - name: Extract short SHA
        id: shortsha
        shell: pwsh
        run: |
          "shortsha=$($env:GITHUB_SHA.Substring(0, 8))" >> $env:GITHUB_OUTPUT

      - name: Compose image tag
        id: imgtag
        shell: pwsh
        run: |
          $imageTag = "${{ steps.versioning.outputs.version }}-dev-g${{ steps.shortsha.outputs.shortsha }}"
          "image_tag=$imageTag" >> $env:GITHUB_OUTPUT

      # Optional: commit updated VERSION file
      # - name: Commit VERSION bump
      #   shell: pwsh
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "github-actions@users.noreply.github.com"
      #     git add VERSION
      #     git commit -m "ci: version bump to ${{ steps.versioning.outputs.version }}"
      #     git push origin HEAD:${{ github.ref_name }}
      #   if: github.ref == 'refs/heads/feature/initial-Setup'


      # --------------------- Sonar + Build ----------------------
      # - name: Start Sonar Analysis
      # - name: Restore NuGet packages
      # - name: Build Solution
      # - name: Run Unit Tests
      # - name: End Sonar Analysis

      - name: Print Docker image tag
        shell: pwsh
        run: |
          echo "Image Tag: ${{ steps.imgtag.outputs.image_tag }}"


     
