name: Dev Build and Sonar Analysis

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - 'feature/*'
  #    - 'fix/*'
  #    - 'docs/*'

jobs:
  build-and-analyze:
    name: Build + Test + Sonar + Optional ECR Push
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      # --------------------- Versioning Step ----------------------
      - name: Bump version from commit
        id: versioning
        shell: pwsh
        run: |
          $CommitMsg = "${{ github.event.head_commit.message }}"
          ./gh-actions-scripts/bump-version.ps1 -CommitMsg $CommitMsg

      - name: Extract short SHA
        id: shortsha
        shell: pwsh
        run: |
          "shortsha=$($env:GITHUB_SHA.Substring(0, 8))" >> $env:GITHUB_OUTPUT

      - name: Compose image tag
        id: imgtag
        shell: pwsh
        run: |
          $imageTag = "${{ steps.versioning.outputs.version }}-dev-g${{ steps.shortsha.outputs.shortsha }}"
          "image_tag=$imageTag" >> $env:GITHUB_OUTPUT

      - name: Print Docker image tag
        shell: pwsh
        run: |
          echo "Image Tag: ${{ steps.imgtag.outputs.image_tag }}"

      # --------------------- Sonar + Build ----------------------
      - name: Start Sonar Analysis
        shell: pwsh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin `
            /k:"DEFRA_apha-bst" `
            /o:"defra" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io"

      - name: Restore NuGet packages
        shell: pwsh
        run: dotnet restore src/Apha.BST.sln

      - name: Build Solution
        shell: pwsh
        run: dotnet build src/Apha.BST.sln --configuration Release

      - name: Run Unit Tests
        shell: pwsh
        run: dotnet test src/Apha.BST.sln --no-build --configuration Release --logger trx

      - name: End Sonar Analysis
        shell: pwsh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
