name: Dev Build and Sonar Analysis
on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
      - 'docs/*'
      - main
permissions: {}   # disables all default permissions           
jobs:
  # 1️⃣ First run the dev build & sonar analysis
  build-and-sonar:
    uses: ./.github/workflows/build-and-sonar-analyze-template.yaml
    with:
      repository: apha/bst
    secrets: 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
    permissions:
      id-token: write
      contents: read  
