- name: Run container locally
        run: |
          # Extract the first tag from metadata output (local tag)
          image_tag=$(echo "${{ steps.meta.outputs.tags }}" | cut -d',' -f1)
          echo "Running local image: $image_tag"
          docker run -d --name test-container -p 8080:8080 "$image_tag"

      - name: Wait for service to start
        run: |
          echo "Waiting for the service to start..."
          for i in {1..10}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 || echo "000")
            echo "HTTP Status: $STATUS"
            if [ "$STATUS" -eq 200 ]; then
              break
            fi
            sleep 3
          done

      - name: Test application response
        run: |
          curl -i http://localhost:8080

      - name: Cleanup container
        if: always()
        run: |
          docker rm -f test-container
